-- Core keymaps (plugin-specific maps live next to each plugin's setup).
local map = vim.keymap.set

map("i", "jk", "<Esc>", { desc = "Exit insert" })
map("n", "<Esc>", "<cmd>nohlsearch<cr><Esc>", { desc = "Clear search highlight" })

-- Save / close (Cursor: ctrl+s, ctrl+x)
map({ "n", "i", "x", "s" }, "<C-s>", "<cmd>write<cr><Esc>", { desc = "Save file" })
map("n", "<C-x>", function()
  Snacks.bufdelete()
end, { desc = "Close buffer" })

-- Windows (Cursor: ctrl+h/j/k/l navigate)
map("n", "<C-h>", "<C-w>h", { desc = "Window left" })
map("n", "<C-j>", "<C-w>j", { desc = "Window down" })
map("n", "<C-k>", "<C-w>k", { desc = "Window up" })
map("n", "<C-l>", "<C-w>l", { desc = "Window right" })
map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase height" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease height" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase width" })
map("n", "<leader>v", "<cmd>vsplit<cr>", { desc = "Split right" })
map("n", "<leader>-", "<cmd>split<cr>", { desc = "Split below" })

-- Buffers (Cursor: H/L next/prev editor)
map("n", "L", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "H", "<cmd>bprevious<cr>", { desc = "Prev buffer" })
map("n", "<leader>bd", function()
  Snacks.bufdelete()
end, { desc = "Delete buffer" })
map("n", "<leader>bD", function()
  Snacks.bufdelete({ force = true })
end, { desc = "Delete buffer (force)" })
map("n", "<leader>bo", function()
  Snacks.bufdelete.other()
end, { desc = "Delete other buffers" })
map("n", "<leader>bc", function()
  Snacks.bufdelete.all()
end, { desc = "Close all buffers" })

-- Move lines (Cursor: alt+shift+j/k)
map("n", "<M-J>", "<cmd>m .+1<cr>==", { desc = "Move line down" })
map("n", "<M-K>", "<cmd>m .-2<cr>==", { desc = "Move line up" })
map("x", "<M-J>", ":m '>+1<cr>gv=gv", { desc = "Move selection down", silent = true })
map("x", "<M-K>", ":m '<-2<cr>gv=gv", { desc = "Move selection up", silent = true })

-- Better defaults
map("x", "<", "<gv")
map("x", ">", ">gv")
map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("x", "p", '"_dP', { desc = "Paste without yanking" })

-- Diagnostics
map("n", "]d", function()
  vim.diagnostic.jump({ count = 1, float = false })
end, { desc = "Next diagnostic" })
map("n", "[d", function()
  vim.diagnostic.jump({ count = -1, float = false })
end, { desc = "Prev diagnostic" })
map("n", "]e", function()
  vim.diagnostic.jump({ count = 1, severity = vim.diagnostic.severity.ERROR })
end, { desc = "Next error" })
map("n", "[e", function()
  vim.diagnostic.jump({ count = -1, severity = vim.diagnostic.severity.ERROR })
end, { desc = "Prev error" })
map("n", "<leader>ld", vim.diagnostic.open_float, { desc = "Line diagnostics" })
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Diagnostics → loclist" })

-- Folds (Cursor: zR / zM)
map("n", "zR", "zR", { desc = "Open all folds" })
map("n", "zM", "zM", { desc = "Close all folds" })

-- Misc
map("n", "<leader>ul", "<cmd>set list!<cr>", { desc = "Toggle whitespace" })
map("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Terminal normal mode" })
map("n", "<leader>pu", "<cmd>PackUpdate<cr>", { desc = "Update plugins" })
map("n", "<leader>pc", "<cmd>PackClean<cr>", { desc = "Clean unused plugins" })
map("n", "<leader>ps", "<cmd>PackStatus<cr>", { desc = "Plugin status" })
map("n", "<leader>pm", "<cmd>Mason<cr>", { desc = "Mason" })
